### ISSUE TITLE
"Code: generalException Message: Unable to deserialize time of day"

### ISSUE THREAD

**Issue by NMarkGraves** [microsoftgraph/msgraph-training-dotnet-core#26]
**Where did you get the code?**
- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
GetMeAsync() catches a ServiceException, "Code: generalException Message: Unable to deserialize time of day"

**To Reproduce**
1. Follow tutorial to the end of page 4
2. Fix bug in DeviceCodeAuthProvider constructor (below)
3. Press F5

OK, u.MailboxSettings is trying to parse something goofy as a date here. No idea what. 

    return await graphClient.Me
        .Request()
        .Select(u => new {
            u.DisplayName
            , u.MailboxSettings
        })
        .GetAsync();

The first time I tried it, GetMeAsync() worked, then I got an exception trying to access the calendar. I didn't take note of what, I just put in a breakpoint and hit F5 again. But every time since, it's been failing in GetMeAsync()

We can't use the API due to the requirement for the user to log in via a web page every time the application runs. But that's a separate issue. 

Also, DeviceCodeAuthProvider doesn't work either. I get "No tenant-identifying information found in either the request or implied by any provided credentials." unless I change this call in the constructor

    .WithAuthority(AadAuthorityAudience.AzureAdAndPersonalMicrosoftAccount, true) 
to this:
    .WithTenantId(OurTenantIDGUID)

**Expected behavior**
I expected it to fail when I listed the calendar, the way it did the first time. But it's failing earlier now. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser n/a
 - Version n/a

**Dependency versions**
 - Microsoft.Identity.Client v4.29.0
 - Microsoft.Graph v4.0.0-preview.2

**Additional context**
Stack trace:

   at Microsoft.Graph.TimeOfDayConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at Microsoft.Graph.DerivedTypeConverter`1.PopulateObject(Object target, JsonElement json, JsonSerializerOptions options)
   at Microsoft.Graph.DerivedTypeConverter`1.Read(Utf8JsonReader& reader, Type objectType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at Microsoft.Graph.DerivedTypeConverter`1.PopulateObject(Object target, JsonElement json, JsonSerializerOptions options)
   at Microsoft.Graph.DerivedTypeConverter`1.Read(Utf8JsonReader& reader, Type objectType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.<ReadAsync>d__19`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.Graph.Serializer.DeserializeObject[T](Stream stream)
   at Microsoft.Graph.ResponseHandler.<HandleResponse>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.UserRequest.<GetAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GraphTutorial.GraphHelper.<GetMeAsync>d__2.MoveNext() in C:\non-dev\WPFExampleCode\Microsoft.Graph.Console\GraphHelper.cs:line 23

**Comment by jasonjoh** [comment]
Regarding the auth provider issue - did you register the application as multi-tenant, or for only users in your tenant?

On the Graph error - that seems to indicate something odd about the response from the Graph service, and the SDK can't deserialize it properly. Can you sign in to [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) with that same user and do a GET on `https://graph.microsoft.com/v1.0/me/mailboxsettings` and post the response?

**Comment by NMarkGraves** [comment]
I think it's only users in our tenant. It's an in-house application. All users will be in our AD.

**Comment by jasonjoh** [comment]
Ok. The only oddity I note is that your `dateFormat` and `timeFormat` properties are empty, which isn't a valid value for those properties. Those don't map to TimeOfDay types though, so I'm not convinced that's the problem. Just to rule it out though, could you login to OWA (outlook.office.com) with that user, go to your [Language and time](https://outlook.office.com/mail/options/general/timeAndLanguage) settings, and choose formats for both date and time, then see if you still get the exception?

On the auth provider: yeah that's expected if you register as single-tenant. Microsoft Identity platform requires you to use your tenant's endpoints for auth, so instead of hitting `https://login.microsoftonline.com/common` like the sample is configured, you have to hit `https://login.microsoftonline.com/YOUR_TENANT_ID`. The code change you made does exactly that :D.

**Comment by NMarkGraves** [comment]
Here's my Language and Time settings from OWA

![image](https://user-images.githubusercontent.com/82244273/114421187-09a8a380-9b83-11eb-86eb-49bc4dc7e4fe.png)

**Comment by jasonjoh** [comment]
Cool can you try again (both in Graph Explorer and the app)? Also, have you ever logged into OWA with that user before?

**Comment by NMarkGraves** [comment]
I've used OWA before, on windows and on iOS.

**Comment by jasonjoh** [comment]
Interesting. So are those values still blank in Graph Explorer?

**Comment by NMarkGraves** [comment]
Same result with the tutorial app. Here's the actual inner exception message that I should have included three days ago: "Invalid leading zero before '8'. LineNumber: 0 | BytePositionInLine: 1."

**Comment by NMarkGraves** [comment]
Still blank in graph explorer

    "dateFormat": "",
    "timeFormat": "",

**Comment by jasonjoh** [comment]
Doh! I just realized you're using the 4.0 preview of the Graph SDK. Seems they have a bug there. I just updated to that version and reproduce the error. Go back to the latest 3.x version and you should be good to go.

**Comment by NMarkGraves** [comment]
Bingo. That worked. Much appreciated!

**Comment by jasonjoh** [comment]
Filed this to track the bug on the SDK side: https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/244

**Comment by NMarkGraves** [comment]
One more thing, if you've got a minute: At some point, we have to make our users do the interactive web page thing, so they can consent to enumerating their own emails or whatever. Thereafter, it's not needed unless we add another scope. 

Is there any way to determine what scopes they've already consented to for the application, other than catching MsalUiRequiredException?

I'd like to spare them the VerificationUrl web page, but I suppose that would be a security hole.

**Comment by jasonjoh** [comment]
Yes and no. The scopes are in the token (it's a JSON Web Token, which is parseable). You can see yourself at https://jwt.ms. However! It's not recommended that you take a dependency on this format, as the token format could change. The recommended pattern from Microsoft identity is to attempt a silent token acquisition first, and if that generates MsalUiRequiredException, then do the interactive request.

If you implement [token cache serialization](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization) and persist your cache between runs of the app, the user may not ever have to login again. If you go that route, you want to take steps to secure wherever you store your cache - that's not something you'd want folks to get access to.
