### ISSUE TITLE
DeviceCodeCredential authentication failed: AADSTS50059 (similar to #2)

### ISSUE THREAD

**Issue by lupino3** [microsoftgraph/msgraph-training-dotnet-core#44]
**Where did you get the code?**
- [x] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

This happens both when I tried the tutorial and also by downloading straight from GitHub.

**Describe the bug**
I am a Microsoft employee (andreas@microsoft.com), and I'm trying to follow the tutorial using an app ID registered on our AAD tenant (microsoft.onmicrosoft.com).
When I run the sample, I get an authentication failure error before getting the prompt to copy-paste the link to sign in:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (DeviceCodeCredential authentication failed: AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.
Trace ID: 1bfdc744-1fef-4cbc-8946-28909b21d100
Correlation ID: 93ccce4f-3fc0-417b-b76a-487a96376a9f
Timestamp: 2022-04-14 13:55:52Z)
 ---> Azure.Identity.AuthenticationFailedException: DeviceCodeCredential authentication failed: AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.
Trace ID: 1bfdc744-1fef-4cbc-8946-28909b21d100
Correlation ID: 93ccce4f-3fc0-417b-b76a-487a96376a9f
Timestamp: 2022-04-14 13:55:52Z
 ---> MSAL.NetCore.4.34.0.0.MsalServiceException:
        ErrorCode: invalid_request
Microsoft.Identity.Client.MsalServiceException: AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.
Trace ID: 1bfdc744-1fef-4cbc-8946-28909b21d100
Correlation ID: 93ccce4f-3fc0-417b-b76a-487a96376a9f
Timestamp: 2022-04-14 13:55:52Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.Internal.Requests.DeviceCodeRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenWithDeviceCodeParameters deviceCodeParameters, CancellationToken cancellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalPublicClient.AcquireTokenWithDeviceCodeCoreAsync(String[] scopes, String claims, Func`2 deviceCodeCallback, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalPublicClient.AcquireTokenWithDeviceCodeAsync(String[] scopes, String claims, Func`2 deviceCodeCallback, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DeviceCodeCredential.GetTokenViaDeviceCodeAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DeviceCodeCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
        StatusCode: 400
        ResponseBody: {"error":"invalid_request","error_description":"AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: 1bfdc744-1fef-4cbc-8946-28909b21d100\r\nCorrelation ID: 93ccce4f-3fc0-417b-b76a-487a96376a9f\r\nTimestamp: 2022-04-14 13:55:52Z","error_codes":[50059],"timestamp":"2022-04-14 13:55:52Z","trace_id":"1bfdc744-1fef-4cbc-8946-28909b21d100","correlation_id":"93ccce4f-3fc0-417b-b76a-487a96376a9f"}
        Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: 93ccce4f-3fc0-417b-b76a-487a96376a9f
x-ms-request-id: 1bfdc744-1fef-4cbc-8946-28909b21d100
x-ms-ests-server: 2.1.12621.9 - NEULR1 ProdSlices
x-ms-clitelem: 1,50059,0,,
X-XSS-Protection: 0
Set-Cookie: fpc=Ale3rwpAXNhHlmS15loRkq7M_PdaAQAAAOge6tkOAAAA; expires=Sat, 14-May-2022 13:55:52 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Thu, 14 Apr 2022 13:55:52 GMT
```

**To Reproduce**

* Download the sample
* use an app-id in our AAD tenant
* set up secrets and run it
 
**Expected behavior**
Ability to run the sample.
 
**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise 22000.613

**Dependency versions**
 - Authentication library (MSAL, etc.) version:
 - Graph library (Graph SDK, REST library, etc.) version:  

Please find attached [project.assets.json.txt](https://github.com/microsoftgraph/msgraph-training-dotnet-core/files/8489737/project.assets.json.txt)

**Comment by jasonjoh** [comment]
@lupino3 unfortunately our IT has disabled your ability to consent to most Microsoft Graph permissions scopes, so using your own identity here won't work without getting admin approval inside the org. If you're just doing testing, you'll want to get a dev tenant. If you really need to access your Microsoft account, contact me internally and I can point you to the process to request approval.

The error your getting is indicating that you registered your app as "my org only", and you're not supplying the org's tenant ID in the configuration of the auth. You would need to replace `common` with your org's tenant ID here:

https://github.com/microsoftgraph/msgraph-training-dotnet-core/blob/e727bcb6e6a6724faf5e8c94a9b20352742a5f33/demo/GraphTutorial/Graph/GraphHelper.cs#L24
